<?php
namespace App\Services;
use Illuminate\Support\Facades\DB;
use RuntimeException;
class GroupBuyingService
{
 public function join(int $userId,int $campaignId):int{return DB::transaction(function()use($userId,$campaignId){$campaign=DB::table('group_buying_campaigns')->where('id',$campaignId)->lockForUpdate()->first();if(!$campaign||$campaign->status!=='active'||($campaign->starts_at&&now()->lt($campaign->starts_at))||($campaign->expires_at&&now()->gt($campaign->expires_at)))throw new RuntimeException('Group buying campaign is not available.');if($campaign->current_buyers>=$campaign->required_buyers)throw new RuntimeException('Group buying target has already been reached.');if(DB::table('group_buying_orders')->where('campaign_id',$campaignId)->where('user_id',$userId)->exists())throw new RuntimeException('You have already joined this group.');$amount=(float)$campaign->price;if($amount<=0)throw new RuntimeException('Invalid group buying price.');$id=DB::table('group_buying_orders')->insertGetId(['campaign_id'=>$campaignId,'user_id'=>$userId,'quantity'=>1,'amount'=>$amount,'status'=>'pending','created_at'=>now(),'updated_at'=>now()]);app(WalletService::class)->debit($userId,$amount,'group_purchase','Immediate payment for group buying campaign #'.$campaignId,'group_buying_order',$id);DB::table('group_buying_orders')->where('id',$id)->update(['status'=>'paid','updated_at'=>now()]);DB::table('group_buying_campaigns')->where('id',$campaignId)->increment('current_buyers');return $id;});}
 public function finalize(int $campaignId):string{return DB::transaction(function()use($campaignId){$campaign=DB::table('group_buying_campaigns')->where('id',$campaignId)->lockForUpdate()->first();if(!$campaign||$campaign->status!=='active')throw new RuntimeException('Campaign is not active.');$met=$campaign->current_buyers>=$campaign->required_buyers;$participants=DB::table('group_buying_orders')->where('campaign_id',$campaignId)->where('status','paid')->lockForUpdate()->get();if($met){DB::table('group_buying_campaigns')->where('id',$campaignId)->update(['status'=>'successful','updated_at'=>now()]);return 'successful';}foreach($participants as $participant){app(WalletService::class)->credit((int)$participant->user_id,(float)$participant->amount,'group_refund','Group buying campaign #'.$campaignId.' did not reach its required buyer condition.','group_buying_order',(int)$participant->id);DB::table('group_buying_orders')->where('id',$participant->id)->update(['status'=>'refunded','updated_at'=>now()]);}DB::table('group_buying_campaigns')->where('id',$campaignId)->update(['status'=>'failed','updated_at'=>now()]);return 'refunded';});}
 public function failCampaign(int $campaignId):void{$this->finalize($campaignId);}
}