<?php
namespace App\Services;
use Illuminate\Support\Facades\DB;
use RuntimeException;
class PaymentService
{
 public function recordPending(int $orderId,string $provider,string $method,float $amount,?string $providerTransactionId=null):int{return DB::table('payments')->insertGetId(['order_id'=>$orderId,'provider'=>$provider,'method'=>$method,'provider_transaction_id'=>$providerTransactionId,'amount'=>$amount,'currency'=>config('chacha.brand.default_currency','USD'),'status'=>'pending','created_at'=>now(),'updated_at'=>now()]);}
 public function markPaid(int $paymentId,?string $providerTransactionId=null):void{DB::transaction(function()use($paymentId,$providerTransactionId){$p=DB::table('payments')->where('id',$paymentId)->lockForUpdate()->first();if(!$p||$p->status==='paid')return;DB::table('payments')->where('id',$paymentId)->update(['status'=>'paid','provider_transaction_id'=>$providerTransactionId?:$p->provider_transaction_id,'paid_at'=>now(),'updated_at'=>now()]);if($p->order_id)DB::table('orders')->where('id',$p->order_id)->update(['status'=>'confirmed','updated_at'=>now()]);});}
 public function markFailed(int $paymentId,?string $reason=null):void{DB::transaction(function()use($paymentId,$reason){$p=DB::table('payments')->where('id',$paymentId)->lockForUpdate()->first();if(!$p||in_array($p->status,['paid','refunded'],true))return;DB::table('payments')->where('id',$paymentId)->update(['status'=>'failed','updated_at'=>now()]);if($p->order_id)DB::table('orders')->where('id',$p->order_id)->update(['status'=>'cancelled','updated_at'=>now()]);});}
 public function refund(int $paymentId,float $amount,?string $reason=null):void{if($amount<=0)throw new RuntimeException('Invalid refund amount.');DB::transaction(function()use($paymentId,$amount,$reason){$p=DB::table('payments')->where('id',$paymentId)->lockForUpdate()->firstOrFail();if(!in_array($p->status,['paid','partially_refunded'],true))throw new RuntimeException('Only paid payments can be refunded.');$ref=(float)DB::table('payment_refunds')->where('payment_id',$paymentId)->where('status','completed')->sum('amount');if($ref+$amount>(float)$p->amount)throw new RuntimeException('Refund exceeds payment amount.');DB::table('payment_refunds')->insert(['payment_id'=>$paymentId,'amount'=>$amount,'reason'=>$reason,'status'=>'completed','created_at'=>now(),'updated_at'=>now()]);$new=$ref+$amount;DB::table('payments')->where('id',$paymentId)->update(['status'=>$new>=(float)$p->amount?'refunded':'partially_refunded','updated_at'=>now()]);});}
}