@extends('layouts.admin')
@section('content')
<div class="space-y-6">
<div class="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Chacha Prime Control Center</p><h1 class="mt-1 text-3xl font-black">Admin Dashboard</h1><p class="mt-1 text-sm text-slate-500">Single-vendor commerce operations overview</p></div><a href="{{ url('/products') }}" class="rounded-xl border bg-white px-4 py-2 text-sm font-semibold shadow-sm">View Storefront</a></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
@foreach([['Orders Today',$stats['orders_today']],['Pending Orders',$stats['pending_orders']],['Shipped',$stats['shipped_orders']],['Delivered',$stats['delivered_orders']],['Customers',$stats['active_customers']],['Open Returns',$stats['open_returns']]] as $card)<div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{$card[0]}}</p><strong class="mt-2 block text-2xl">{{$card[1]}}</strong></div>@endforeach
</div>
<div class="grid gap-4 md:grid-cols-4"><div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Revenue Today</p><strong class="mt-2 block text-2xl">{{number_format($stats['revenue_today'],2)}} {{config('chacha.brand.default_currency','USD')}}</strong></div><div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Lifetime Revenue</p><strong class="mt-2 block text-2xl">{{number_format($stats['revenue_total'],2)}} {{config('chacha.brand.default_currency','USD')}}</strong></div><div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Wallet Balance</p><strong class="mt-2 block text-2xl">{{number_format($stats['wallet_balance'],2)}} {{config('chacha.brand.default_currency','USD')}}</strong></div><div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Pending Reviews</p><strong class="mt-2 block text-2xl">{{$stats['pending_reviews']}}</strong></div></div>
<div class="grid gap-6 lg:grid-cols-[1fr_360px]">
<div class="space-y-6"><div class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-xl font-bold">Recent Orders</h2><a href="{{url('/admin/orders')}}" class="text-sm font-semibold text-blue-600">View all</a></div><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="px-2 py-3">Order</th><th class="px-2 py-3">Status</th><th class="px-2 py-3">Payment</th><th class="px-2 py-3 text-right">Total</th></tr></thead><tbody>@forelse($recentOrders as $order)<tr class="border-b last:border-0"><td class="px-2 py-4 font-semibold">{{$order->order_number}}</td><td class="px-2 py-4">{{ucfirst(str_replace('_',' ',$order->status))}}</td><td class="px-2 py-4">{{ucfirst($order->payment_status)}}</td><td class="px-2 py-4 text-right font-semibold">{{number_format($order->total_amount,2)}} {{$order->currency}}</td></tr>@empty<tr><td colspan="4" class="px-2 py-10 text-center text-slate-500">No orders yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="grid gap-6 md:grid-cols-2"><div class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex justify-between"><h2 class="text-lg font-bold">New Customers</h2><a href="{{route('admin.customers.index')}}" class="text-sm text-blue-600">View all</a></div><div class="mt-3 divide-y">@forelse($recentCustomers as $c)<a href="{{route('admin.customers.show',$c->id)}}" class="flex justify-between py-3"><span><b>{{$c->name}}</b><span class="block text-xs text-slate-500">{{$c->email}}</span></span><span class="text-xs">{{ucfirst($c->status??'active')}}</span></a>@empty<p class="py-5 text-sm text-slate-500">No customers yet.</p>@endforelse</div></div><div class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex justify-between"><h2 class="text-lg font-bold">Pending Reviews</h2><a href="{{route('admin.reviews.index')}}" class="text-sm text-blue-600">Moderate</a></div><div class="mt-3 divide-y">@forelse($pendingReviews as $r)<div class="py-3"><b>{{$r->product_title}}</b><span class="block text-xs text-slate-500">{{$r->customer_name}} · {{$r->rating}}/5</span></div>@empty<p class="py-5 text-sm text-slate-500">No pending reviews.</p>@endforelse</div></div></div></div>
<div class="space-y-6"><div class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-lg font-bold">Low Stock</h2><a href="{{route('admin.products.index')}}" class="text-sm text-blue-600">Products</a></div><div class="mt-3 divide-y">@forelse($lowStock as $product)<div class="flex justify-between gap-4 py-3"><div><p class="font-semibold">{{$product->title}}</p><p class="text-xs text-slate-500">{{$product->sku}}</p></div><strong class="text-red-600">{{$product->stock_qty}}</strong></div>@empty<p class="py-6 text-sm text-slate-500">No low-stock products.</p>@endforelse</div></div><div class="rounded-3xl border bg-slate-950 p-6 text-white shadow-sm"><p class="text-xs font-semibold uppercase tracking-[.2em] text-slate-400">Operations</p><div class="mt-4 grid grid-cols-2 gap-2 text-sm"><a href="{{route('admin.products.index')}}" class="rounded-xl bg-white/10 px-3 py-3">Products</a><a href="{{route('admin.orders.index')}}" class="rounded-xl bg-white/10 px-3 py-3">Orders</a><a href="{{route('admin.customers.index')}}" class="rounded-xl bg-white/10 px-3 py-3">Customers</a><a href="{{route('admin.reviews.index')}}" class="rounded-xl bg-white/10 px-3 py-3">Reviews</a><a href="{{route('admin.returns.index')}}" class="rounded-xl bg-white/10 px-3 py-3">Returns</a></div></div></div>
</div></div>
@endsection
