<?php
namespace App\Http\Controllers\Customer;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class AccountController extends Controller {
 public function dashboard(Request $r){return app(DashboardController::class)->index();}
 public function orders(Request $r){return view('customer.orders',['orders'=>DB::table('orders')->where('user_id',$r->user()->id)->latest()->paginate(15)]);}
 public function order(Request $r,int $order){$item=DB::table('orders')->where('id',$order)->where('user_id',$r->user()->id)->firstOrFail();$items=DB::table('order_items')->where('order_id',$order)->get();$shipment=DB::table('shipments')->where('order_id',$order)->latest('id')->first();$payments=DB::table('payments')->where('order_id',$order)->latest('id')->get();$events=DB::table('order_status_history')->where('order_id',$order)->orderBy('created_at')->get();return view('customer.orders.show',['order'=>$item,'items'=>$items,'shipment'=>$shipment,'payments'=>$payments,'events'=>$events]);}
 public function cancel(Request $r,int $order){DB::transaction(function()use($order,$r){$o=DB::table('orders')->where('id',$order)->where('user_id',$r->user()->id)->lockForUpdate()->firstOrFail();abort_unless(in_array($o->status,['pending','confirmed']),422,'This order can no longer be cancelled.');foreach(DB::table('order_items')->where('order_id',$order)->get() as $i)app(\App\Services\InventoryService::class)->restore((int)$i->product_id,$i->variant_id?(int)$i->variant_id:null,(int)$i->quantity,'cancel_restore','order',$order,$r->user()->id);$payment=DB::table('payments')->where('order_id',$order)->where('status','paid')->latest('id')->lockForUpdate()->first();if($payment&&$payment->provider==='chacha_wallet'){app(\App\Services\WalletService::class)->credit((int)$r->user()->id,(float)$payment->amount,'refund','Order cancellation refund','order_cancel',$order);DB::table('payments')->where('id',$payment->id)->update(['status'=>'refunded','updated_at'=>now()]);}elseif($payment){app(\App\Services\PaymentService::class)->refund((int)$payment->id,(float)$payment->amount,'Order cancellation refund');}DB::table('orders')->where('id',$order)->update(['status'=>'cancelled','updated_at'=>now()]);DB::table('order_status_history')->insert(['order_id'=>$order,'status'=>'cancelled','note'=>'Customer cancelled order','created_by'=>$r->user()->id,'created_at'=>now()]);});return back()->with('success','Order cancelled, inventory restored, and applicable payment refund processed.');}
}