<?php
namespace App\Http\Controllers\Customer;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class WishlistReviewController extends Controller
{
 public function wishlist(Request $r){$items=DB::table('wishlist_items')->join('products','products.id','=','wishlist_items.product_id')->where('wishlist_items.user_id',$r->user()->id)->where('products.status','active')->select('wishlist_items.product_id','products.title','products.slug','products.retail_price')->latest('wishlist_items.created_at')->paginate(20);return view('customer.wishlist',compact('items'));}
 public function add(Request $r,int $product){DB::table('products')->where('id',$product)->where('status','active')->firstOrFail();DB::table('wishlist_items')->insertOrIgnore(['user_id'=>$r->user()->id,'product_id'=>$product,'created_at'=>now()]);return back()->with('success','Product added to wishlist.');}
 public function remove(Request $r,int $product){DB::table('wishlist_items')->where('user_id',$r->user()->id)->where('product_id',$product)->delete();return back()->with('success','Product removed from wishlist.');}
 public function storeReview(Request $r,int $product){$d=$r->validate(['rating'=>'required|integer|min:1|max:5','title'=>'nullable|string|max:255','body'=>'required|string|max:2000']);$p=DB::table('products')->where('id',$product)->firstOrFail();$item=DB::table('orders')->join('order_items','orders.id','=','order_items.order_id')->where('orders.user_id',$r->user()->id)->where('order_items.product_id',$product)->where('orders.status','delivered')->select('orders.id as order_id','order_items.id as order_item_id')->latest('orders.id')->first();abort_unless($item,403,'You can review products you purchased and received.');$review=DB::table('reviews')->where('user_id',$r->user()->id)->where('product_id',$product)->first();$payload=['rating'=>$d['rating'],'title'=>$d['title']??null,'body'=>$d['body'],'status'=>'pending','order_item_id'=>$item->order_item_id,'updated_at'=>now()];if($review)DB::table('reviews')->where('id',$review->id)->update($payload);else DB::table('reviews')->insert(array_merge(['user_id'=>$r->user()->id,'product_id'=>$product,'created_at'=>now()],$payload));return back()->with('success','Review submitted for moderation.');}
}