@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-7xl space-y-6">
<div><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Payments</p><h1 class="text-3xl font-black">Payment Provider Center</h1><p class="text-sm text-slate-500">Configure checkout providers. Secret credentials remain server-side and are never displayed here.</p></div>
@if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{{session('success')}}</div>@endif
<div class="grid gap-6 lg:grid-cols-3">
<form method="POST" action="{{route('admin.payment-methods.store')}}" class="rounded-3xl border bg-white p-6 space-y-4 shadow-sm">@csrf<h2 class="text-xl font-bold">Add provider</h2><input name="name" required placeholder="Display name" class="w-full rounded-xl border px-4 py-3"><input name="provider" required placeholder="Provider key" class="w-full rounded-xl border px-4 py-3"><input name="sort_order" type="number" min="0" value="0" class="w-full rounded-xl border px-4 py-3"><label class="flex items-center gap-2 text-sm"><input name="enabled" value="1" type="checkbox" checked> Enable at checkout</label><button class="w-full rounded-xl bg-slate-950 px-4 py-3 font-bold text-white">Add provider</button></form>
<div class="lg:col-span-2 space-y-4">@forelse($methods as $m)
<div class="rounded-3xl border bg-white p-5 shadow-sm"><form method="POST" action="{{route('admin.payment-methods.update',$m->id)}}" class="grid gap-3 md:grid-cols-2">@csrf @method('PUT')
<label class="text-sm font-semibold">Display name<input name="name" value="{{$m->name}}" required class="mt-1 w-full rounded-xl border px-4 py-3"></label><label class="text-sm font-semibold">Provider key<input name="provider" value="{{$m->provider}}" required class="mt-1 w-full rounded-xl border px-4 py-3"></label><label class="text-sm font-semibold">Sort order<input name="sort_order" type="number" min="0" value="{{$m->sort_order}}" class="mt-1 w-full rounded-xl border px-4 py-3"></label><div class="flex items-end gap-2"><label class="flex items-center gap-2 text-sm"><input name="enabled" value="1" type="checkbox" @checked($m->enabled)> Enabled</label><button class="ml-auto rounded-xl bg-slate-950 px-4 py-3 font-bold text-white">Save</button></div>
</form><div class="mt-3 flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span class="text-sm text-slate-500">Secrets are managed through server environment configuration.</span><form method="POST" action="{{route('admin.payment-methods.toggle',$m->id)}}">@csrf @method('PATCH')<button class="rounded-xl px-4 py-2 font-bold {{$m->enabled?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'}}">{{$m->enabled?'Enabled':'Disabled'}}</button></form></div>
</div>
@empty<div class="rounded-3xl border bg-white p-8 text-center text-slate-500">No payment methods configured yet.</div>@endforelse</div></div></div>
@endsection