@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
<section class="overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-12 text-white sm:px-10 lg:px-14"><p class="text-xs font-bold uppercase tracking-[.3em] text-blue-300">Chacha Prime</p><h1 class="mt-4 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Premium shopping for retail, wholesale and group buying.</h1><p class="mt-5 max-w-2xl text-slate-300">Discover products, compare buying options and unlock group prices from one secure marketplace.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ url('/products') }}" class="rounded-2xl bg-white px-6 py-3 font-bold text-slate-950">Shop products</a><a href="{{ url('/categories') }}" class="rounded-2xl border border-white/20 px-6 py-3 font-bold">Browse categories</a></div></section>
<section class="mt-10"><div class="flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.25em] text-blue-600">Explore</p><h2 class="mt-2 text-2xl font-black">Shop by category</h2></div><a href="{{ url('/categories') }}" class="text-sm font-bold text-blue-600">View all</a></div><div class="mt-5 grid gap-4 grid-cols-2 md:grid-cols-4 lg:grid-cols-6">@foreach(($categories ?? []) as $category)<a href="{{ url('/category/'.$category->slug) }}" class="rounded-2xl border bg-white p-5 font-bold shadow-sm transition hover:-translate-y-0.5">{{ $category->name }}</a>@endforeach</div></section>
<section class="mt-12"><div class="flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.25em] text-blue-600">Trending now</p><h2 class="mt-2 text-2xl font-black">Featured products</h2></div><a href="{{ url('/products') }}" class="text-sm font-bold text-blue-600">View all</a></div><div class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach(($products ?? []) as $product)<article class="overflow-hidden rounded-3xl border bg-white shadow-sm"><a href="{{ url('/product/'.$product->slug) }}"><div class="aspect-square bg-slate-100"><img src="{{ $product->primary_image ?? asset('images/placeholder-product.webp') }}" alt="{{ $product->title }}" class="h-full w-full object-cover"></div><div class="p-5"><p class="line-clamp-2 font-bold">{{ $product->title }}</p><p class="mt-3 text-xl font-black">{{ $product->retail_price }}</p><p class="mt-1 text-xs text-slate-500">{{ $product->monthly_bought ?? 0 }} bought this month</p></div></a></article>@endforeach</div></section>
<section class="mt-12 rounded-[2rem] border bg-white p-7 shadow-sm"><div class="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p class="text-xs font-bold uppercase tracking-[.25em] text-blue-600">Group buying</p><h2 class="mt-2 text-2xl font-black">Unlock a lower price together</h2><p class="mt-2 text-slate-500">Join an active campaign, pay immediately and receive the amount in your Chacha Wallet if the required condition is not met.</p></div><a href="{{ url('/group-buying') }}" class="rounded-2xl bg-slate-950 px-6 py-3 text-center font-bold text-white">Explore group buying</a></div></section>
</div>
@endsection
