@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
 <div class="grid gap-8 lg:grid-cols-[1.05fr_.95fr]">
  <section><div class="aspect-square overflow-hidden rounded-[2rem] border bg-slate-50"><img src="{{ $product->primary_image ?? asset('images/placeholder-product.webp') }}" alt="{{ $product->title ?? 'Product' }}" class="h-full w-full object-cover"></div><div class="mt-4 grid grid-cols-4 gap-3"><div class="aspect-square rounded-2xl border bg-slate-50"></div><div class="aspect-square rounded-2xl border bg-slate-50"></div><div class="aspect-square rounded-2xl border bg-slate-50"></div><div class="aspect-square rounded-2xl border bg-slate-50"></div></div></section>
  <section><div class="flex flex-wrap gap-2"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{ $product->brand_name ?? 'Chacha Prime' }}</span><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">In stock</span></div><h1 class="mt-4 text-3xl font-black tracking-tight sm:text-4xl">{{ $product->title ?? 'Premium Product' }}</h1><div class="mt-3 flex flex-wrap items-center gap-4 text-sm"><span class="font-bold">★ {{ $product->rating ?? '0.0' }}</span><span class="text-slate-500">{{ $product->review_count ?? 0 }} reviews</span><span class="text-slate-500">SKU: {{ $product->sku ?? 'CP-SKU' }}</span></div><p class="mt-5 text-slate-600">{{ $product->short_description ?? 'Discover product details, specifications, variations and delivery options.' }}</p>
   <div class="mt-6 rounded-3xl border bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-widest text-slate-500">Retail price</p><p class="mt-1 text-3xl font-black">{{ $product->retail_price ?? '$0.00' }}</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-2xl bg-slate-50 p-4"><p class="text-xs text-slate-500">Wholesale</p><p class="mt-1 font-black">{{ $product->wholesale_price ?? '$0.00' }}</p></div><div class="rounded-2xl bg-blue-50 p-4"><p class="text-xs text-blue-600">Group buying</p><p class="mt-1 font-black text-blue-700">{{ $product->group_price ?? '$0.00' }}</p></div></div></div>
   <div class="mt-5"><p class="font-bold">Variations</p><div class="mt-3 flex flex-wrap gap-2"><button class="rounded-xl border px-4 py-2 text-sm font-semibold">Default</button><button class="rounded-xl border px-4 py-2 text-sm font-semibold">Option 2</button><button class="rounded-xl border px-4 py-2 text-sm font-semibold">Option 3</button></div></div>
   <div class="mt-6 grid gap-3 sm:grid-cols-2"><a href="{{ url('/cart') }}" class="rounded-2xl border px-5 py-4 text-center font-black">Add to cart</a><button class="rounded-2xl bg-slate-950 px-5 py-4 font-black text-white">Buy now</button></div><button class="mt-3 w-full rounded-2xl bg-blue-600 px-5 py-4 font-black text-white">Join group buying</button>
   <div class="mt-6 grid gap-3 sm:grid-cols-2"><div class="rounded-2xl border p-4"><p class="font-bold">Shipping</p><p class="mt-1 text-sm text-slate-500">Economy up to 7 business days • Express available</p></div><div class="rounded-2xl border p-4"><p class="font-bold">Returns</p><p class="mt-1 text-sm text-slate-500">7 business days after receipt</p></div></div>
  </section>
 </div>
 <div class="mt-10 grid gap-6 lg:grid-cols-3"><section class="rounded-3xl border bg-white p-6 lg:col-span-2"><h2 class="text-xl font-black">Product details</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><div><p class="font-bold">Highlights</p><p class="mt-1 text-sm text-slate-500">Key product benefits and features.</p></div><div><p class="font-bold">Specifications</p><p class="mt-1 text-sm text-slate-500">Technical and product specifications.</p></div><div><p class="font-bold">Fulfillment</p><p class="mt-1 text-sm text-slate-500">Ship from seller or Chacha Prime marketplace fulfillment.</p></div><div><p class="font-bold">Buyer activity</p><p class="mt-1 text-sm text-slate-500">{{ $product->monthly_bought ?? 0 }} bought this month.</p></div></div></section><aside class="rounded-3xl bg-slate-950 p-6 text-white"><p class="text-sm font-semibold text-blue-300">Secure shopping</p><h2 class="mt-2 text-xl font-black">Payment & protection</h2><ul class="mt-5 space-y-3 text-sm text-slate-300"><li>✓ Secure transaction</li><li>✓ Order tracking</li><li>✓ Return/replacement support</li><li>✓ QR-enabled invoice</li></ul></aside></div>
</div>
@endsection
