@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-6xl px-4 py-8">
 <div class="mb-8"><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Chacha Prime Checkout</p><h1 class="mt-2 text-3xl font-black tracking-tight">Choose your payment method</h1><p class="mt-2 text-sm text-slate-500">Secure checkout. Card details are handled by the payment provider and are never stored here.</p></div>
 <div class="grid gap-6 lg:grid-cols-[1fr_360px]">
  <section class="rounded-3xl border bg-white p-5 shadow-sm"><div id="paymentMethods" class="space-y-3"><div class="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Loading payment methods...</div></div><button id="payButton" type="button" class="mt-6 w-full rounded-2xl bg-slate-950 px-5 py-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Continue securely</button><p id="message" class="mt-3 text-sm"></p></section>
  <aside class="rounded-3xl border bg-slate-950 p-6 text-white"><p class="text-sm text-slate-400">Order total</p><p id="total" class="mt-2 text-3xl font-black">{{ $currency ?? 'USD' }} {{ number_format((float)($amount ?? 0),2) }}</p><div class="mt-6 space-y-3 border-t border-white/10 pt-5 text-sm"><div class="flex justify-between"><span class="text-slate-400">Payment security</span><span>Protected</span></div><div class="flex justify-between"><span class="text-slate-400">Order</span><span>#{{ $orderId ?? '' }}</span></div></div></aside>
 </div>
</div>
<script>
const orderId={{ (int)($orderId ?? 0) }}, amount={{ (float)($amount ?? 0) }}, currency=@json($currency ?? 'USD');let selected='';
async function loadMethods(){const r=await fetch('{{ url('/customer/checkout/payment-methods') }}',{headers:{Accept:'application/json'}});const j=await r.json();const box=document.getElementById('paymentMethods');box.innerHTML=(j.methods||[]).map((m,i)=>`<label class="flex cursor-pointer items-center gap-4 rounded-2xl border p-4 transition hover:border-slate-950"><input type="radio" name="payment" value="${m.provider}" ${i===0?'checked':''} class="h-5 w-5"><span><strong class="block">${m.name}</strong><small class="text-slate-500">${m.provider==='wallet'?'Use your Chacha Wallet balance':m.provider==='cod'?'Pay when your order arrives':'Continue with secure provider checkout'}</small></span></label>`).join('');selected=box.querySelector('input:checked')?.value||'';box.onchange=e=>{if(e.target.name==='payment')selected=e.target.value};}
document.getElementById('payButton').onclick=async()=>{const b=document.getElementById('payButton'),msg=document.getElementById('message');b.disabled=true;msg.textContent='Processing...';try{const r=await fetch('{{ url('/customer/checkout/payment') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({order_id:orderId,provider:selected,amount,currency})});const j=await r.json();if(!r.ok)throw new Error(j.message||'Payment could not be processed.');msg.textContent=j.status==='paid'?'Payment completed successfully.':j.status==='authorized'?'Order payment authorized.':'Payment created; continue with the provider if required.';}catch(e){msg.textContent=e.message}finally{b.disabled=false}};loadMethods();
</script>
@endsection
