@extends('layouts.storefront')
@section('content')
<div class="container mx-auto max-w-7xl px-4 py-10 space-y-7">
<div class="rounded-[2rem] bg-slate-950 p-7 text-white shadow-xl"><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-300">My Chacha Prime</p><h1 class="mt-2 text-3xl font-black">Customer Dashboard</h1><p class="mt-2 text-slate-300">Orders, delivery tracking, wallet, returns and account controls in one place.</p></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><a href="{{route('customer.orders')}}" class="rounded-3xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Total orders</p><strong class="mt-2 block text-2xl">{{$stats['orders']??$orders->count()}}</strong></a><div class="rounded-3xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Active orders</p><strong class="mt-2 block text-2xl">{{$stats['pending']??0}}</strong></div><div class="rounded-3xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Delivered</p><strong class="mt-2 block text-2xl">{{$stats['delivered']??0}}</strong></div><a href="{{route('customer.wallet')}}" class="rounded-3xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Wallet balance</p><strong class="mt-2 block text-2xl">{{number_format((float)($wallet??0),2)}}</strong></a></div>
<div class="grid gap-6 lg:grid-cols-3"><div class="rounded-3xl border bg-white p-6 shadow-sm lg:col-span-2"><div class="flex items-center justify-between"><h2 class="text-xl font-black">Recent Orders</h2><a class="text-sm font-semibold text-blue-600" href="{{route('customer.orders')}}">View all</a></div><div class="mt-5 space-y-2">@forelse($orders as $order)<a href="{{route('customer.orders.show',$order->id)}}" class="flex items-center justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div><strong>{{$order->order_number}}</strong><p class="text-sm text-slate-500">{{ucwords(str_replace('_',' ',$order->status))}}</p></div><strong>{{number_format($order->total_amount,2)}} {{$order->currency}}</strong></a>@empty<p class="py-8 text-center text-slate-500">No orders yet.</p>@endforelse</div></div>
<div class="space-y-6"><div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Active Deliveries</h2><div class="mt-4 space-y-3">@forelse($shipments??[] as $s)<a href="{{route('customer.orders.tracking',$s->order_id)}}" class="block rounded-2xl bg-slate-50 p-4"><b>{{$s->order_number}}</b><p class="text-sm text-slate-500">{{ucwords(str_replace('_',' ',$s->status))}} · {{$s->tracking_number?:'Tracking pending'}}</p></a>@empty<p class="text-sm text-slate-500">No active deliveries.</p>@endforelse</div></div><div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Quick Access</h2><div class="mt-4 grid gap-2"><a class="rounded-xl bg-slate-50 px-4 py-3" href="{{route('customer.wallet')}}">Wallet & Ledger</a><a class="rounded-xl bg-slate-50 px-4 py-3" href="{{route('customer.returns')}}">Returns & Refunds</a><a class="rounded-xl bg-slate-50 px-4 py-3" href="#">Addresses</a><a class="rounded-xl bg-slate-50 px-4 py-3" href="{{route('customer.wishlist')}}">Wishlist</a><a class="rounded-xl bg-slate-50 px-4 py-3" href="{{route('products.index')}}">Reviews</a><a class="rounded-xl bg-slate-50 px-4 py-3" href="{{route('customer.security')}}">Security & 2FA</a></div></div></div></div>
<div class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-xl font-black">Notifications</h2><span class="text-sm text-slate-500">Recent account activity</span></div><div class="mt-4 grid gap-3 md:grid-cols-2">@forelse($notifications??[] as $n)<div class="rounded-2xl bg-slate-50 p-4"><b>{{$n->title}}</b><p class="mt-1 text-sm text-slate-600">{{$n->message}}</p></div>@empty<p class="text-sm text-slate-500">No new notifications.</p>@endforelse</div></div>
</div>@endsection
