@extends('layouts.admin')

@section('content')
<div class="mx-auto max-w-6xl space-y-6">
    <div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Catalog Builder</p><h1 class="mt-1 text-3xl font-bold">Create Product</h1></div>
    <form method="POST" action="{{ route('admin.products.store') }}" enctype="multipart/form-data" class="space-y-6">
        @csrf
        <div class="grid gap-6 lg:grid-cols-2">
            <div class="rounded-3xl border bg-white p-6 shadow-sm lg:col-span-2"><h2 class="text-lg font-bold">Basic information</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><input name="name" required placeholder="Product name" class="rounded-xl border px-4 py-3"><input name="title" required placeholder="Product title" class="rounded-xl border px-4 py-3"><input name="sku" required placeholder="Unique SKU" class="rounded-xl border px-4 py-3"><input name="brand_name" placeholder="Brand name" class="rounded-xl border px-4 py-3"><textarea name="short_description" placeholder="Short description" class="rounded-xl border px-4 py-3 md:col-span-2"></textarea><textarea name="description" rows="7" placeholder="Long description" class="rounded-xl border px-4 py-3 md:col-span-2"></textarea><textarea name="highlights" rows="5" placeholder="Highlights — one per line" class="rounded-xl border px-4 py-3 md:col-span-2"></textarea></div></div>
            <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Pricing & stock</h2><div class="mt-4 grid gap-4"><input name="retail_price" type="number" step="0.01" required placeholder="Retail price" class="rounded-xl border px-4 py-3"><input name="wholesale_price" type="number" step="0.01" placeholder="Wholesale price" class="rounded-xl border px-4 py-3"><input name="group_buying_price" type="number" step="0.01" placeholder="Group buying price" class="rounded-xl border px-4 py-3"><input name="stock_qty" type="number" min="0" required placeholder="Stock quantity" class="rounded-xl border px-4 py-3"></div></div>
            <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Media</h2><p class="mt-1 text-sm text-slate-500">Upload gallery images and product videos.</p><div class="mt-4 space-y-4"><input name="images[]" type="file" multiple accept="image/*" class="block w-full rounded-xl border p-3"><input name="videos[]" type="file" multiple accept="video/*" class="block w-full rounded-xl border p-3"></div></div>
            <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Specifications</h2><textarea name="specifications" rows="8" placeholder="Material: ...&#10;Size: ...&#10;Weight: ..." class="mt-4 w-full rounded-xl border px-4 py-3"></textarea></div>
            <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Shipping & returns</h2><div class="mt-4 grid gap-4"><select name="shipping_template" class="rounded-xl border px-4 py-3"><option value="economy">Economy — up to 7 days — Free</option><option value="express">Express — additional charge</option><option value="custom">Custom shipping template</option></select><select name="fulfillment" class="rounded-xl border px-4 py-3"><option value="seller">Ship from seller</option><option value="marketplace">Ship from Chacha Prime Marketplace (FBA)</option></select><input name="return_window_days" type="number" min="0" value="7" class="rounded-xl border px-4 py-3" placeholder="Return window (business days)"></div></div>
            <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">AI & category</h2><p class="mt-1 text-sm text-slate-500">Category recommendation can be generated from the product title, description and specifications.</p><select name="category_mode" class="mt-4 w-full rounded-xl border px-4 py-3"><option value="ai">AI recommend category</option><option value="manual">Select manually</option></select></div>
        </div>
        <button class="rounded-2xl bg-slate-950 px-7 py-4 font-bold text-white">Create Product & Generate QR</button>
    </form>
</div>
@endsection
