@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-7xl space-y-6">
<div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Catalog Management</p><h1 class="mt-1 text-3xl font-bold">{{ isset($item)?'Edit Product':'Create Product' }}</h1></div>
@if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{{session('success')}}</div>@endif
@if($errors->any())<div class="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{isset($item)?route('admin.products.update',$item->id):route('admin.products.store')}}" class="space-y-6">@csrf @if(isset($item)) @method('PUT') @endif
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Product Identity</h2><div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
@foreach([['title','Storefront Title'],['sku','SKU']] as $f)<label><span class="text-sm font-semibold">{{$f[1]}}</span><input name="{{$f[0]}}" value="{{old($f[0],$item->{$f[0]}??'')}}" @if(in_array($f[0],['title','sku'])) required @endif class="mt-2 w-full rounded-xl border p-3"></label>@endforeach
<label><span class="text-sm font-semibold">Category</span><select name="category_id" class="mt-2 w-full rounded-xl border p-3"><option value="">Select category</option>@foreach($categories as $c)<option value="{{$c->id}}" @selected(old('category_id',$item->category_id??'')==$c->id)>{{$c->name}}</option>@endforeach</select></label></div>
<div class="mt-4 grid gap-4 md:grid-cols-2"><textarea name="short_description" rows="3" placeholder="Short description" class="rounded-xl border p-3">{{old('short_description',$item->short_description??'')}}</textarea><textarea name="description" rows="5" placeholder="Full description" class="rounded-xl border p-3">{{old('description',$item->description??'')}}</textarea></div></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Pricing & Inventory</h2><div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach([['retail_price','Retail Price'],['wholesale_price','Wholesale Price'],['group_price','Group-buy Price'],['cost_price','Cost Price'],['stock_qty','Stock Quantity'],['low_stock_threshold','Low-stock Threshold']] as $f)<label><span class="text-sm font-semibold">{{$f[1]}}</span><input type="number" step="0.01" min="0" name="{{$f[0]}}" value="{{old($f[0],$item->{$f[0]}??0)}}" class="mt-2 w-full rounded-xl border p-3"></label>@endforeach</div></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Variants</h2><div class="mt-4 grid gap-3 md:grid-cols-6"><input id="v_sku" placeholder="Variant SKU" class="rounded-xl border p-3"><input id="v_attr" name="attributes" placeholder='Attributes JSON' class="rounded-xl border p-3"><input id="v_price" type="number" step=".01" placeholder="Retail" class="rounded-xl border p-3"><input id="v_stock" type="number" min="0" placeholder="Stock" class="rounded-xl border p-3"><button type="button" onclick="addVariant()" class="rounded-xl bg-slate-950 px-4 font-bold text-white">Add</button></div><div class="mt-5 space-y-2">@foreach(($variations??[]) as $v)<div class="flex flex-wrap items-center justify-between rounded-2xl bg-slate-50 p-4"><div><b>{{json_encode($v->attributes)}}</b> <span class="text-xs text-slate-500">{{$v->sku}}</span></div><div>Stock {{$v->stock_qty}} · {{number_format($v->price??0,2)}}</div><form method="POST" action="{{route('admin.products.variations.delete',[$item->id,$v->id])}}">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Remove</button></form></div>@endforeach</div></section>
@if(isset($item))<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Inventory Adjustment</h2><form method="POST" action="{{route('admin.products.inventory',$item->id)}}" class="mt-4 flex flex-wrap gap-3">@csrf<input name="adjustment" type="number" placeholder="+10 / -2" required class="rounded-xl border p-3"><input name="reason" placeholder="Reason" required class="min-w-64 rounded-xl border p-3"><button class="rounded-xl bg-slate-950 px-5 font-bold text-white">Adjust Stock</button></form></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Media</h2><form method="POST" action="{{route('admin.products.media.store',$item->id)}}" class="mt-4 flex flex-wrap gap-3">@csrf<input name="path" placeholder="Image/video URL or storage path" required class="min-w-80 flex-1 rounded-xl border p-3"><select name="type" class="rounded-xl border p-3"><option value="image">Image</option><option value="video">Video</option></select><button class="rounded-xl bg-slate-950 px-5 font-bold text-white">Add Media</button></form><div class="mt-4 grid gap-3 md:grid-cols-3">@foreach(($media??[]) as $m)<div class="rounded-2xl border p-3"><div class="truncate text-sm">{{$m->path}}</div><div class="mt-2 flex justify-between text-xs"><span>{{$m->type}}</span><form method="POST" action="{{route('admin.products.media.delete',[$item->id,$m->id])}}">@csrf @method('DELETE')<button class="text-red-600">Delete</button></form></div></div>@endforeach</div></section>
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-bold">QR Product Identity</h2><code class="mt-3 block break-all rounded-xl bg-slate-50 p-4 text-xs">{{$item->qr_value}}</code><p class="mt-2 text-sm text-slate-500">Every product is identified by its unique SKU QR payload.</p></section>@endif
<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-bold">SEO & Status</h2><div class="mt-4 grid gap-4 md:grid-cols-3"><input name="ship_from" placeholder="Ship from" value="{{old('ship_from',$item->ship_from??'')}}" class="rounded-xl border p-3"><div class="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">Product QR identity is generated automatically from SKU.</div><select name="status" class="rounded-xl border p-3"><option value="draft">Draft</option><option value="active" @selected(($item->status??'')==='active')>Active</option><option value="inactive">Inactive</option><option value="out_of_stock">Out of Stock</option><option value="archived">Archived</option></select></div></section>
<div class="flex justify-end"><button class="rounded-2xl bg-slate-950 px-7 py-3 font-bold text-white">{{isset($item)?'Save Product':'Create Product'}}</button></div>
</form></div>
<script>function addVariant(){let f=new FormData();f.append('_token','{{csrf_token()}}');f.append('sku',v_sku.value);f.append('attributes',v_attr.value||'{}');f.append('price',v_price.value);f.append('stock_qty',v_stock.value);fetch('{{isset($item)?route('admin.products.variations.store',$item->id):'#'}}',{method:'POST',body:f}).then(()=>location.reload())}</script>
@endsection
