@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
 <div class="mb-8"><p class="text-xs font-bold uppercase tracking-[.25em] text-blue-600">Chacha Prime Checkout</p><h1 class="mt-2 text-3xl font-black tracking-tight">Secure checkout</h1><p class="mt-1 text-slate-500">Review your order, choose delivery and pay securely.</p></div>
 <div class="grid gap-6 lg:grid-cols-[1fr_380px]">
  <div class="space-y-6">
   <section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-bold">1. Delivery address</h2><a href="#" class="text-sm font-semibold text-blue-600">Change</a></div><div class="mt-4 rounded-2xl border p-4"><p class="font-semibold">Default delivery address</p><p class="mt-1 text-sm text-slate-500">Add your delivery address from your account before placing the order.</p></div></section>
   <section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-bold">2. Shipping method</h2><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="flex cursor-pointer items-center justify-between rounded-2xl border p-4"><span><span class="block font-semibold">Economy</span><span class="text-sm text-slate-500">Up to 7 business days</span></span><span class="font-bold">FREE</span></label><label class="flex cursor-pointer items-center justify-between rounded-2xl border p-4"><span><span class="block font-semibold">Express</span><span class="text-sm text-slate-500">Faster delivery</span></span><span class="font-bold">Paid</span></label></div></section>
   <section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-bold">3. Payment method</h2><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="rounded-2xl border p-4"><span class="font-semibold">Wallet</span><span class="mt-1 block text-sm text-slate-500">Use Chacha Wallet balance, bonuses or credits.</span></label><label class="rounded-2xl border p-4"><span class="font-semibold">Card / Online</span><span class="mt-1 block text-sm text-slate-500">Payment provider checkout.</span></label><label class="rounded-2xl border p-4"><span class="font-semibold">Cash on Delivery</span><span class="mt-1 block text-sm text-slate-500">Delivery charges are paid first.</span></label><label class="rounded-2xl border p-4"><span class="font-semibold">Bank / Local payment</span><span class="mt-1 block text-sm text-slate-500">Available providers shown at payment.</span></label></div></section>
   <section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Gift option</h2><label class="mt-4 flex items-center gap-3"><input type="checkbox" class="rounded"><span class="text-sm">This is a gift</span></label><textarea class="mt-4 w-full rounded-2xl border p-3" rows="3" placeholder="Gift message (optional)"></textarea></section>
  </div>
  <aside class="h-fit rounded-3xl border bg-slate-950 p-6 text-white shadow-xl"><h2 class="text-lg font-bold">Order summary</h2><div class="mt-6 space-y-3 text-sm"><div class="flex justify-between text-slate-300"><span>Subtotal</span><span>$0.00</span></div><div class="flex justify-between text-slate-300"><span>Shipping</span><span>FREE</span></div><div class="flex justify-between text-slate-300"><span>Discount</span><span>$0.00</span></div><div class="my-4 border-t border-white/10"></div><div class="flex justify-between text-lg font-black"><span>Total</span><span>$0.00</span></div></div><button type="button" class="mt-6 w-full rounded-2xl bg-white px-5 py-4 font-black text-slate-950 transition hover:opacity-90">Place order securely</button><p class="mt-4 text-center text-xs text-slate-400">Secure transaction • Gift option • Order tracking</p></aside>
 </div>
</div>
@endsection
