@extends('layouts.storefront')
@section('title',$product->title.' | Chacha Prime')
@section('content')
<section class="container mx-auto px-4 py-8 md:py-12">
<div class="grid gap-10 lg:grid-cols-2">
<div><div class="aspect-square overflow-hidden rounded-[2rem] bg-slate-100 ring-1 ring-slate-200">@if($product->media->first())<img id="main-product-image" src="{{asset($product->media->first()->path)}}" alt="{{$product->title}}" class="h-full w-full object-cover">@else<div class="flex h-full items-center justify-center text-slate-400">No product image</div>@endif</div><div class="mt-3 grid grid-cols-6 gap-2">@foreach($product->media as $media) @if(($media->media_type??$media->type??'image')==='image')<button type="button" onclick="document.getElementById('main-product-image').src='{{asset($media->path)}}'" class="aspect-square overflow-hidden rounded-xl border bg-white"><img src="{{asset($media->path)}}" class="h-full w-full object-cover"></button>@endif @endforeach</div></div>
<div>
@if($product->brand)<p class="text-xs font-bold uppercase tracking-[.2em] text-blue-600">{{$product->brand->name}}</p>@endif
<h1 class="mt-2 text-3xl font-black tracking-tight md:text-5xl">{{$product->title}}</h1><p class="mt-3 text-sm text-slate-500">SKU: {{$product->sku}}</p>
<div class="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center gap-3"><span id="display-price" class="text-4xl font-black">{{number_format($product->retail_price,2)}} {{config('chacha.brand.default_currency')}}</span>@if($product->wholesale_price)<span class="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">Wholesale {{number_format($product->wholesale_price,2)}}</span>@endif @if($product->group_price)<span class="rounded-full bg-orange-50 px-3 py-1 text-sm font-bold text-orange-700">Group {{number_format($product->group_price,2)}}</span>@endif</div>@if($product->short_description)<p class="mt-4 leading-7 text-slate-600">{{$product->short_description}}</p>@endif<div class="mt-5 flex items-center gap-3"><span class="h-2.5 w-2.5 rounded-full {{$product->stock_qty>0?'bg-emerald-500':'bg-red-500'}}"></span><span class="text-sm font-semibold">{{$product->stock_qty>0?'In stock':'Out of stock'}}</span></div></div>
@if($product->variants->count())<div class="mt-7"><h2 class="font-bold">Choose variation</h2><div class="mt-3 flex flex-wrap gap-2">@foreach($product->variants as $v)<button type="button" data-variant="{{$v->id}}" data-stock="{{$v->stock_qty}}" data-price="{{$v->price}}" class="variant-btn rounded-xl border px-4 py-2 text-left text-sm font-semibold hover:border-slate-950"><span class="block">{{$v->sku}}</span><span class="mt-1 block text-xs font-normal text-slate-500">{{number_format((float)$v->price,2)}} {{config('chacha.brand.default_currency')}} · {{$v->stock_qty>0?'In stock':'Out of stock'}}</span></button>@endforeach</div></div>@endif
@auth<form method="POST" action="{{route('cart.add')}}" class="mt-7 flex gap-3">@csrf<input type="hidden" name="product_id" value="{{$product->id}}"><input type="hidden" name="variant_id" id="selected-variant" value=""><div class="flex items-center rounded-2xl border"><button type="button" onclick="qty.value=Math.max(1,+qty.value-1)" class="px-4 py-3">−</button><input id="qty" name="quantity" value="1" min="1" max="99" type="number" class="w-14 border-x py-3 text-center"><button type="button" onclick="qty.value=+qty.value+1" class="px-4 py-3">+</button></div><button type="submit" id="add-cart" class="flex-1 rounded-2xl bg-slate-950 px-5 py-4 font-bold text-white {{$product->stock_qty<1?'opacity-50':''}}" {{$product->stock_qty<1?'disabled':''}}>Add to Cart</button></form>@else<a href="{{url('/login')}}" class="mt-7 block rounded-2xl bg-slate-950 px-5 py-4 text-center font-bold text-white">Sign in to add to cart</a>@endauth
<div class="mt-5 grid gap-3 sm:grid-cols-2"><div class="rounded-2xl border p-4"><b>Shipping</b><p class="mt-1 text-sm text-slate-500">Delivery options and cost are calculated at checkout.</p></div><div class="rounded-2xl border p-4"><b>Returns</b><p class="mt-1 text-sm text-slate-500">{{$product->return_window_business_days??7}} business days after receipt.</p></div></div>
</div></div>
<div class="mt-14 grid gap-8 lg:grid-cols-3"><div class="lg:col-span-2"><h2 class="text-2xl font-black">Product details</h2><div class="mt-4 leading-8 text-slate-600">{!!nl2br(e($product->description))!!}</div></div><aside class="rounded-3xl border bg-white p-6 shadow-sm">@auth
<form method="POST" action="{{route('customer.wishlist.add',$product->id)}}" class="mb-5">@csrf<button class="w-full rounded-2xl border px-4 py-3 font-bold">Add to Wishlist</button></form>
@endauth
<h2 class="font-bold">Secure transaction</h2><p class="mt-2 text-sm leading-6 text-slate-500">Payments are processed through supported providers. Chacha Prime does not store real card details.</p><div class="mt-5 rounded-2xl bg-slate-50 p-4"><b>Product QR identity</b><code class="mt-2 block break-all text-xs text-slate-500">{{$product->qr_value??''}}</code></div></aside></div>
</section>
<script>document.querySelectorAll('.variant-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.variant-btn').forEach(x=>x.classList.remove('bg-slate-950','text-white'));b.classList.add('bg-slate-950','text-white');document.getElementById('selected-variant').value=b.dataset.variant;document.getElementById('qty').max=Math.max(1,+b.dataset.stock);document.getElementById('qty').value=1;document.getElementById('add-cart').disabled=+b.dataset.stock<1;document.getElementById('display-price').textContent=Number(b.dataset.price).toFixed(2)+' {{config('chacha.brand.default_currency')}}';}));</script>
@endsection
