<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Services\PaymentGatewayManager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class PaymentCenterController extends Controller
{
 public function index(Request $request){$base=DB::table('payment_transactions');$stats=['pending'=>(clone $base)->where('status','pending')->count(),'paid'=>(clone $base)->where('status','paid')->count(),'failed'=>(clone $base)->where('status','failed')->count(),'refunded'=>(clone $base)->whereIn('status',['refunded','partially_refunded'])->count()];$q=DB::table('payment_transactions as p')->leftJoin('orders as o','o.id','=','p.order_id')->leftJoin('users as u','u.id','=','p.user_id')->select('p.*','o.order_number','u.name as customer_name','u.email as customer_email')->when($request->search,fn($x,$v)=>$x->where(function($w)use($v){$w->where('o.order_number','like','%'.$v.'%')->orWhere('p.transaction_reference','like','%'.$v.'%')->orWhere('u.email','like','%'.$v.'%');}))->when($request->status,fn($x,$v)=>$x->where('p.status',$v))->latest('p.id')->paginate(25)->withQueryString();return view('admin.payments.index',['payments'=>$q,'stats'=>$stats]);}
 public function show(int $payment){$p=DB::table('payment_transactions as p')->leftJoin('orders as o','o.id','=','p.order_id')->leftJoin('users as u','u.id','=','p.user_id')->select('p.*','o.order_number','u.name as customer_name','u.email')->where('p.id',$payment)->firstOrFail();$webhooks=DB::table('payment_webhooks')->where('provider',$p->provider)->latest()->limit(20)->get();return view('admin.payments.show',compact('p','webhooks'));}
 public function markStatus(Request $request,int $payment){$data=$request->validate(['status'=>'required|in:pending,authorized,paid,failed,cancelled,refunded,partially_refunded']);DB::table('payment_transactions')->where('id',$payment)->update(['status'=>$data['status'],'updated_at'=>now(),'paid_at'=>$data['status']==='paid'?now():null]);return back()->with('success','Payment status updated.');}
 public function refund(Request $request,int $payment,PaymentGatewayManager $gateways){$tx=DB::table('payment_transactions')->where('id',$payment)->firstOrFail();$data=$request->validate(['amount'=>'required|numeric|min:0.01']);abort_if($data['amount']>$tx->amount,422,'Refund exceeds payment amount.');$result=$gateways->refund($tx->provider,(string)($tx->provider_reference??$tx->transaction_reference),(float)$data['amount']);DB::table('payment_transactions')->where('id',$payment)->update(['status'=>'pending','failure_message'=>null,'updated_at'=>now()]);return back()->with('success','Refund request queued: '.($result['status']??'pending').'.');}
}
