<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class ShippingController extends Controller
{
 public function index(){return view('admin.shipping.index',['zones'=>DB::table('shipping_zones')->latest()->get(),'methods'=>DB::table('shipping_methods')->latest()->get(),'shipments'=>DB::table('shipments')->join('orders','orders.id','=','shipments.order_id')->select('shipments.*','orders.order_number')->latest('shipments.id')->paginate(25)]);}
 public function createShipment(Request $r,int $order){$d=$r->validate(['shipping_method_id'=>'nullable|integer','carrier'=>'nullable|string|max:120','tracking_number'=>'nullable|string|max:190','tracking_url'=>'nullable|url|max:500']);$id=DB::table('shipments')->insertGetId(['order_id'=>$order,'shipping_method_id'=>$d['shipping_method_id']??null,'carrier'=>$d['carrier']??null,'tracking_number'=>$d['tracking_number']??null,'tracking_url'=>$d['tracking_url']??null,'status'=>$d['tracking_number']?'label_created':'pending','created_at'=>now(),'updated_at'=>now()]);DB::table('shipment_events')->insert(['shipment_id'=>$id,'status'=>$d['tracking_number']?'label_created':'pending','description'=>'Shipment created','event_at'=>now(),'created_at'=>now()]);return back()->with('success','Shipment created.');}
 public function updateShipment(Request $r,int $shipment){$d=$r->validate(['status'=>'required|in:pending,label_created,picked_up,in_transit,out_for_delivery,delivered,exception,returned','tracking_number'=>'nullable|string|max:190','carrier'=>'nullable|string|max:120','tracking_url'=>'nullable|url|max:500','location'=>'nullable|string|max:190','description'=>'nullable|string|max:500']);DB::transaction(function()use($shipment,$d){$s=DB::table('shipments')->where('id',$shipment)->lockForUpdate()->firstOrFail();$update=['status'=>$d['status'],'updated_at'=>now()];foreach(['tracking_number','carrier','tracking_url'] as $f)if(array_key_exists($f,$d))$update[$f]=$d[$f];if($d['status']==='in_transit'&&!$s->shipped_at)$update['shipped_at']=now();if($d['status']==='delivered'&&!$s->delivered_at)$update['delivered_at']=now();DB::table('shipments')->where('id',$shipment)->update($update);DB::table('shipment_events')->insert(['shipment_id'=>$shipment,'status'=>$d['status'],'description'=>$d['description']??null,'location'=>$d['location']??null,'event_at'=>now(),'created_at'=>now()]);});return back()->with('success','Shipment updated.');}
}
