<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class ShippingController extends Controller
{
 public function index(){return view('admin.shipping.index',['zones'=>DB::table('shipping_zones')->latest()->get(),'methods'=>DB::table('shipping_methods')->latest()->get(),'shipments'=>DB::table('shipments')->join('orders','orders.id','=','shipments.order_id')->select('shipments.*','orders.order_number')->latest('shipments.id')->paginate(25)]);}
 public function createShipment(Request $r,int $order){$d=$r->validate(['shipping_method_id'=>'nullable|integer','carrier'=>'nullable|string|max:120','service'=>'nullable|string|max:120','tracking_number'=>'nullable|string|max:190','estimated_delivery_date'=>'nullable|date','notes'=>'nullable|string|max:2000']);$id=DB::table('shipments')->insertGetId(['order_id'=>$order,'shipping_method_id'=>$d['shipping_method_id']??null,'carrier'=>$d['carrier']??null,'service'=>$d['service']??null,'tracking_number'=>$d['tracking_number']??null,'status'=>'pending','estimated_delivery_date'=>$d['estimated_delivery_date']??null,'notes'=>$d['notes']??null,'created_at'=>now(),'updated_at'=>now()]);DB::table('shipment_events')->insert(['shipment_id'=>$id,'status'=>'pending','message'=>'Shipment created','event_at'=>now(),'created_at'=>now()]);return back()->with('success','Shipment created.');}
 public function updateShipment(Request $r,int $shipment){$d=$r->validate(['status'=>'required|in:pending,packed,dispatched,in_transit,out_for_delivery,delivered,returned,exception','tracking_number'=>'nullable|string|max:190','carrier'=>'nullable|string|max:120','service'=>'nullable|string|max:120','location'=>'nullable|string|max:190','message'=>'nullable|string|max:500']);DB::transaction(function()use($shipment,$d){$s=DB::table('shipments')->where('id',$shipment)->lockForUpdate()->firstOrFail();$update=['status'=>$d['status'],'updated_at'=>now()];foreach(['tracking_number','carrier','service'] as $f)if(array_key_exists($f,$d))$update[$f]=$d[$f];if($d['status']==='in_transit'&&!$s->shipped_at)$update['shipped_at']=now();if($d['status']==='delivered'&&!$s->delivered_at)$update['delivered_at']=now();DB::table('shipments')->where('id',$shipment)->update($update);DB::table('shipment_events')->insert(['shipment_id'=>$shipment,'status'=>$d['status'],'message'=>$d['message']??null,'location'=>$d['location']??null,'event_at'=>now(),'created_at'=>now()]);});return back()->with('success','Shipment updated.');}
}
