@extends('layouts.storefront')
@section('content')
<div class="container mx-auto max-w-7xl px-4 py-10"><div class="mb-8"><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Chacha Prime</p><h1 class="mt-1 text-4xl font-black">Your Cart</h1></div>
@if(session('success'))<div class="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{{session('success')}}</div>@endif
@if(count($cart['items']))
<div class="grid gap-7 lg:grid-cols-[1fr_380px]"><form method="POST" action="{{route('cart.update')}}" class="space-y-3">@csrf @foreach($cart['items'] as $item)<div class="flex gap-4 rounded-3xl border bg-white p-4 shadow-sm"><div class="h-28 w-28 shrink-0 overflow-hidden rounded-2xl bg-slate-100">@if($item['product']->media->first())<img src="{{asset($item['product']->media->first()->path)}}" class="h-full w-full object-cover">@endif</div><div class="min-w-0 flex-1"><h2 class="font-bold">{{$item['product']->title}}</h2><p class="mt-1 text-xs text-slate-500">SKU: {{$item['product']->sku}} @if($item['variant']) · {{$item['variant']->name}} @endif</p><div class="mt-4 flex items-center justify-between gap-3"><div><span class="font-black">{{number_format($item['price'],2)}} {{config('chacha.brand.default_currency')}}</span><input type="hidden" name="items[{{$loop->index}}][key]" value="{{$item['key']}}"><input name="items[{{$loop->index}}][quantity]" value="{{$item['quantity']}}" min="0" max="99" type="number" class="ml-3 w-20 rounded-xl border p-2"></div><a href="{{route('cart.remove',$item['key'])}}" class="text-sm font-semibold text-red-600">Remove</a></div></div></div>@endforeach<button class="rounded-2xl border px-6 py-3 font-bold">Update Cart</button></form>
<aside class="h-fit rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Order Summary</h2><div class="mt-5 space-y-3 text-sm"><div class="flex justify-between"><span>Subtotal</span><b>{{number_format($cart['subtotal'],2)}} {{config('chacha.brand.default_currency')}}</b></div><div class="flex justify-between text-slate-500"><span>Shipping</span><span>Calculated at checkout</span></div></div><div class="my-5 border-t"></div><div class="flex justify-between text-lg font-black"><span>Total</span><span>{{number_format($cart['total'],2)}} {{config('chacha.brand.default_currency')}}</span></div><a href="{{route('checkout.index')}}" class="mt-6 block rounded-2xl bg-slate-950 px-5 py-4 text-center font-bold text-white">Proceed to Checkout</a></aside></div>
@else<div class="rounded-3xl border bg-white p-14 text-center"><h2 class="text-2xl font-bold">Your cart is empty</h2><p class="mt-2 text-slate-500">Add products from Chacha Prime to get started.</p><a href="{{route('products.index')}}" class="mt-6 inline-block rounded-2xl bg-slate-950 px-6 py-3 font-bold text-white">Continue Shopping</a></div>@endif</div>
@endsection
