@extends('layouts.storefront')
@section('content')
<div class="min-h-screen bg-slate-50 px-4 py-8 sm:py-12"><div class="mx-auto max-w-7xl">
<div class="mb-8 flex flex-col gap-2"><span class="text-xs font-black uppercase tracking-[.22em] text-blue-600">Chacha Prime</span><h1 class="text-3xl font-black tracking-tight sm:text-4xl">Secure Checkout</h1><p class="text-sm text-slate-500">Complete your delivery and payment details.</p></div>
@if($errors->any())<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><b>Please check the following:</b><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{route('checkout.place')}}" class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_390px]" id="checkout-form">@csrf
<div class="space-y-6">
<section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
<div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-slate-950 text-sm font-black text-white">1</span><div><h2 class="text-lg font-black">Delivery address</h2><p class="text-xs text-slate-500">Select a saved address from your account.</p></div></div>
<div class="mt-6 space-y-3">
@forelse($addresses as $address)
<label class="flex cursor-pointer gap-4 rounded-2xl border border-slate-200 p-4 transition has-[:checked]:border-slate-950 has-[:checked]:ring-2 has-[:checked]:ring-slate-100"><input type="radio" name="shipping_address_id" value="{{$address->id}}" required class="mt-1 h-4 w-4" @checked($address->is_default && $address->type==='shipping')><span><b class="block">{{$address->full_name}}</b><span class="text-sm text-slate-600">{{$address->address_line_1}}{{ $address->address_line_2 ? ', '.$address->address_line_2 : '' }}, {{$address->city}}{{ $address->state ? ', '.$address->state : '' }} {{$address->postal_code}}, {{$address->country_code}}</span>@if($address->phone)<span class="mt-1 block text-xs text-slate-500">{{$address->phone}}</span>@endif</span></label>
@empty
<div class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">No saved address found. Add a shipping address from your account before checkout.</div>
@endforelse
</div>
<a href="{{route('customer.addresses')}}" class="mt-4 inline-block text-sm font-bold text-blue-600">Manage addresses</a>
<input type="hidden" name="billing_address_id" id="billing_address_id" value="{{old('billing_address_id')}}">
</section>
<section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-slate-950 text-sm font-black text-white">2</span><div><h2 class="text-lg font-black">Delivery method</h2><p class="text-xs text-slate-500">Choose how you want your order delivered.</p></div></div><div class="mt-6 space-y-3" id="shipping-options">@forelse($shipping_quotes as $quote)<label class="flex cursor-pointer items-center justify-between gap-4 rounded-2xl border border-slate-200 p-4 transition hover:border-slate-950 has-[:checked]:border-slate-950 has-[:checked]:ring-2 has-[:checked]:ring-slate-100"><div class="flex items-start gap-3"><input type="radio" name="shipping_rate_id" value="{{$quote['id']}}" data-rate="{{$quote['rate']}}" data-name="{{$quote['name']}}" required class="mt-1 h-4 w-4" @checked($loop->first)><div><b class="block">{{$quote['name']}}</b><span class="text-xs text-slate-500">{{$quote['carrier'] ?: 'Chacha Prime Delivery'}} · @if($quote['estimated_days_min']) {{$quote['estimated_days_min']}}–{{$quote['estimated_days_max']}} business days @else Delivery estimate shown after dispatch @endif</span></div></div><strong class="whitespace-nowrap">{{number_format($quote['rate'],2)}} {{config('chacha.brand.default_currency')}}</strong></label>@empty<div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">No shipping method is currently available for this country.</div>@endforelse</div></section>
<section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-slate-950 text-sm font-black text-white">3</span><div><h2 class="text-lg font-black">Payment</h2><p class="text-xs text-slate-500">Choose your payment method.</p></div></div><div class="mt-6 grid gap-3 sm:grid-cols-2"><label class="cursor-pointer rounded-2xl border border-slate-200 p-4 transition has-[:checked]:border-slate-950 has-[:checked]:ring-2 has-[:checked]:ring-slate-100"><input type="radio" name="payment_method" value="wallet" checked class="mr-2"><b>Chacha Wallet</b><p class="mt-2 text-xs text-slate-500">Available balance: {{number_format($wallet,2)}} {{config('chacha.brand.default_currency')}}</p></label><label class="cursor-pointer rounded-2xl border border-slate-200 p-4 transition has-[:checked]:border-slate-950 has-[:checked]:ring-2 has-[:checked]:ring-slate-100"><input type="radio" name="payment_method" value="cod" class="mr-2"><b>Cash on Delivery</b><p class="mt-2 text-xs text-slate-500">Pay when your order arrives.</p></label></div></section>
<section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="text-lg font-black">Coupon</h2><div class="mt-4 flex gap-2"><input name="coupon_code" value="{{old('coupon_code')}}" placeholder="Enter coupon code" class="min-w-0 flex-1 rounded-2xl border border-slate-200 p-3.5"><button type="button" class="rounded-2xl border px-5 font-bold">Apply</button></div><p class="mt-2 text-xs text-slate-400">Coupon eligibility is verified securely when the order is placed.</p></section>
</div>
<aside class="h-fit lg:sticky lg:top-6"><div class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="text-xl font-black">Order Summary</h2><div class="mt-6 space-y-3 text-sm"><div class="flex justify-between"><span class="text-slate-500">Subtotal</span><b id="subtotal">{{number_format($cart['subtotal'],2)}} {{config('chacha.brand.default_currency')}}</b></div><div class="flex justify-between"><span class="text-slate-500">Shipping</span><b id="shipping-total">{{number_format(($shipping_quotes[0]['rate']??0),2)}} {{config('chacha.brand.default_currency')}}</b></div></div><div class="my-5 border-t"></div><div class="flex items-end justify-between"><span class="font-bold">Estimated total</span><strong id="grand-total" class="text-2xl font-black">{{number_format($cart['subtotal']+($shipping_quotes[0]['rate']??0),2)}} {{config('chacha.brand.default_currency')}}</strong></div><button type="submit" id="place-order" @disabled(empty($shipping_quotes)) class="mt-6 w-full rounded-2xl bg-slate-950 px-5 py-4 font-black text-white transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-40">Place Order Securely</button><p class="mt-4 text-center text-xs text-slate-400">Your order and payment information are processed securely.</p></div></aside>
</form></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('checkout-form'),country=document.getElementById('country_code'),options=document.getElementById('shipping-options'),shipping=document.getElementById('shipping-total'),total=document.getElementById('grand-total'),subtotal={{json_encode((float)$cart['subtotal'])}},currency={{json_encode(config('chacha.brand.default_currency'))}};function update(){const address=form.querySelector('input[name="shipping_address_id"]:checked');if(address)document.getElementById('billing_address_id').value=address.value;const selected=form.querySelector('input[name="shipping_rate_id"]:checked');const rate=selected?Number(selected.dataset.rate):0;shipping.textContent=rate.toFixed(2)+' '+currency;total.textContent=(subtotal+rate).toFixed(2)+' '+currency;}options?.addEventListener('change',update);form.querySelectorAll('input[name="shipping_address_id"]').forEach(x=>x.addEventListener('change',update));country?.addEventListener('change',()=>{const url=new URL(window.location.href);url.searchParams.set('country_code',country.value);window.location.href=url.toString();});update();});</script>
@endsection
